name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Checkout distribution repository
        uses: actions/checkout@v2
        with:
          repository: bs-community/plugins-dist
          path: '.dist'
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.26.0
      - name: Download nano
        run: ./download-nano.ps1
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./nano
        env:
          RUST_LOG: info
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: ./publish.ps1
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
